#define SCULL_IOC_MAGIC 'k'
#define SCULL_IOCSETDATA _IOW(SCULL_IOC_MAGIC,0,int) 
#define SCULL_IOCGETDATA _IOR(SCULL_IOC_MAGIC,1,int) 
#define SCULL_IOCCREATPIPE _IO(SCULL_IOC_MAGIC,2) 
#define SCULL_IOCDELETEPIPE _IO(SCULL_IOC_MAGIC,3) 

#define SCULL_IOC_MAXNR 5
